#if defined _shop_sms_const_included
	#endinput
#endif
#define _shop_sms_const_included

#pragma library "shop_sms_const"

#define VERSION "2.3.2"

#define PREFIX "SKLEP-SMS"

#define SS_OK -1
#define SS_WRONG -2
#define SS_ERROR -3
#define SS_REPEAT -4
#define SS_EXISTS -5
#define SS_CREATED -6
#define SS_MODULE -7
#define SS_SERVICE -8
#define SS_STOP -9

#define MAX_ILOSC_SMS 11
#define MAX_MODUL_TRESC 32
#define MAX_USLUGA_TAG 16
#define MAX_NAZWA 32
#define MAX_OPIS 28
#define MAX_KOD 16
#define MAX_CONFIG 512

#define ITEM_OFF 3
